export const PERMISSIONS = {
  // USER MANAGEMENT
  USERS_VIEW: 'USERS_VIEW',
  USERS_CREATE: 'USERS_CREATE',
  USERS_EDIT: 'USERS_EDIT',
  USERS_DELETE: 'USERS_DELETE',
  USER_TYPES_MANAGE: 'USER_TYPES_MANAGE',

  // TASK MANAGEMENT
  TASKS_VIEW_ALL: 'TASKS_VIEW_ALL',
  TASKS_CREATE: 'TASKS_CREATE',
  TASKS_ASSIGN: 'TASKS_ASSIGN',
  TASKS_EDIT: 'TASKS_EDIT',
  TASKS_DELETE: 'TASKS_DELETE',

  // ATTENDANCE & OFFICES
  ATTENDANCE_VIEW_ALL: 'ATTENDANCE_VIEW_ALL',
  ATTENDANCE_MANAGE: 'ATTENDANCE_MANAGE',
  OFFICES_MANAGE: 'OFFICES_MANAGE',

  // SALARY & PAYROLL
  SALARY_VIEW_ALL: 'SALARY_VIEW_ALL',
  SALARY_MANAGE: 'SALARY_MANAGE',
  SALARY_GENERATE: 'SALARY_GENERATE',

  // SYSTEM & REPORTS
  REPORTS_VIEW: 'REPORTS_VIEW',
  AUDIT_LOGS_VIEW: 'AUDIT_LOGS_VIEW',
  GLOBAL_CONFIG_MANAGE: 'GLOBAL_CONFIG_MANAGE',

  // SPECIAL
  SUPER_ADMIN: 'all'
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export type PermissionValue = typeof PERMISSIONS[PermissionKey];
